version: "3"
services: 
    python: # ここの名前とdevcontainer.jsonの"service"を一致させる
        build: .    # 同階層のdockerfileからビルドする
        command: >
            sh -c "nvidia-smi && sleep infinity"
        volumes: 
            - ../:/code  # 上階層のディレクトリをDocker Container上のworkdirにマウント
        environment: 
            SHELL: /bin/bash
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]